### ISSUE TITLE
Create Failure: QSDashboardNestedStackQSDashboardNestedStackResourceF5171359

### ISSUE THREAD

**Issue by alfredcs** [awslabs/discovering-hot-topics-using-machine-learning#19]
**Describe the bug**
Got the following error when starting CloudFormation Template from AWS Console. 

CREATE_FAILED | Parameter QuickSightSourceTemplateArn failed to satisfy constraint: Provide an arn matching an Amazon Quicksight template arn. The input did not match the validation pattern.

On IAM I have a policy defined like this,

...

        {
            "Effect": "Allow",
            "Action": [
                "quicksight:*"
            ],
            "Resource": [
                "arn:aws:quicksight:*:*:*"
            ]
        },

I am working on us-west-2 but looking into the template file it has a line like the following. Is it possible that us-east-1 which caused the issue?

"Parameters": {
          "QuickSightSourceTemplateArn": "arn:aws:quicksight:us-east-1:mltest:template/default_discovering-hot-topics_0_2",
          "QuickSightPrincipalArn": {
            "Ref": "QuickSightPrincipalArn"
          },

Thank you!

**Comment by knihit** [comment]
Hi @alfredcs, thank you for reaching out. Looking at the scenario, looking at the above information, seems like the template Arn is missing AWS account ID. If you can check the parent/ main template on how the template Arn is passed. The Arn format should be as below.

arn:aws:quicksight:us-east-1:**<AWSAccountID>**:template/solutions-features_discovering-hot-topics-using-machine-learning_v1_5_1-pv-prototype.

To answer your specific question, region should not matter. You can deploy the solution in any region while the templates may still be in us-east-1. You can also deploy the solution from this location. https://s3.amazonaws.com/solutions-reference/discovering-hot-topics-using-machine-learning/latest/discovering-hot-topics-using-machine-learning.template. 

The landing page of the solution is as follows: https://aws.amazon.com/solutions/implementations/discovering-hot-topics-using-machine-learning/.

Please reach out if you still face an issue.

**Comment by alfredcs** [comment]
Thanks @Knihit for getting back.

After update the template file discovering-hot-topics-using-machine-learning.template with "QuickSightSourceTemplateArn": "arn:aws:quicksight:us-east-1:976939723775:template/solutions-features_discovering-hot-topics-using-machine-learning_v1_5_1-pv-prototype", I was able to complete the deployment successfully. 

The IAM policy was intended to allow a designated user to launch Quicksight. Also it would be nice to publish post implementation samples to on consumption.  

Thank you for the great post and your comprehensive answer!

**Comment by knihit** [comment]
Hi @alfredcs , happy to hear that your issue is resolved. If you are looking for post implementation screenshots, you can go have a look at the implementation guide here. https://docs.aws.amazon.com/solutions/latest/discovering-hot-topics-using-machine-learning/welcome.html. This guide also has use cases to better understand how to use the QuickSight dashboard. If there is anything else you need help with, please feel free to reach out.

**Comment by knihit** [comment]
Hi @alfredcs , hope all issues you had was resolved. If so, can we close this issue.

**Comment by aassadza** [comment]
Hi @alfredcs , thank you for your inquiry and suggestions. Please let us know if you need additional assistance here. Closing this issue for now.
