### ISSUE TITLE
Quicksign dependency

### ISSUE THREAD

**Issue by bazooka720** [awslabs/discovering-hot-topics-using-machine-learning#8]
Whats the best way to remove any dependency to quicksight (basically not use quicksight at all but keep everything else)?

**Comment by aassadza** [comment]
Hey @bazooka720, thanks for your question and marking the enhancement label. You can customize the solution code to remove the dependency to Amazon QuickSight by removing the nested stack `QuickSightStack` in the code and rebuilding the solution.

In this solution, we specifically designed the QuickSight portion of the functionality as nested stack for better separation. Refer to https://github.com/awslabs/discovering-hot-topics-using-machine-learning/blob/5aba8dcf98d9d64b985f47d0875962912c7ae50b/source/lib/discovering-hot-topics-stack.ts#L132 and other references to QuickSight and the nested template `qsNestedTemplate` variable in the same file. One option is to add a CfnParameter to the CloudFormation of the solution to conditionally create or not create the QuickSight resources. Another option is to remove the code for creation of QuickSightStack object in source/lib/discovering-hot-topics-stack.ts and its related code (also in other files).

Are you looking for an option to enable / disable Amazon QuickSight functionality when deploying the solution? Or an option to remove (or not use) the Amazon QuickSight code during the build of the solution?

**Comment by aassadza** [comment]
Hey @bazooka720, closing this issue for now, but please let us know if you have any further questions/suggestions to discuss. Thanks.
